Attribute VB_Name = "modKey"
'---------------------------------------------------------------------------------------
' Module    : modKey
' DateTime  : 2013-04-03 13:36
' Author    : YJSoft
' Purpose   :
'---------------------------------------------------------------------------------------
Option Explicit
Public Declare Sub keybd_event Lib "user32" (ByVal bVk As Byte, ByVal bScan As Byte, ByVal dwFlags As Long, ByVal dwExtraInfo As Long)
Public Const KEYEVENTF_EXTENDEDKEY = &H1
Public Const KEYEVENTF_KEYUP = &H2

Public Const VK_0 = &H30
Public Const VK_1 = &H31
Public Const VK_2 = &H32
Public Const VK_3 = &H33
Public Const VK_4 = &H34
Public Const VK_5 = &H35
Public Const VK_6 = &H36
Public Const VK_7 = &H37
Public Const VK_8 = &H38
Public Const VK_9 = &H39
Public Const VK_A = &H41
Public Const VK_B = &H42
Public Const VK_C = &H43
Public Const VK_D = &H44
Public Const VK_E = &H45
Public Const VK_F = &H46
Public Const VK_G = &H47
Public Const VK_H = &H48
Public Const VK_I = &H49
Public Const VK_J = &H4A
Public Const VK_K = &H4B
Public Const VK_L = &H4C
Public Const VK_M = &H4D
Public Const VK_N = &H4E
Public Const VK_O = &H4F
Public Const VK_P = &H50
Public Const VK_Q = &H51
Public Const VK_R = &H52
Public Const VK_S = &H53
Public Const VK_T = &H54
Public Const VK_U = &H55
Public Const VK_V = &H56
Public Const VK_W = &H57
Public Const VK_X = &H58
Public Const VK_Y = &H59
Public Const VK_Z = &H5A

Public Const VK_ADD = &H6B
Public Const VK_ATTN = &HF6
Public Const VK_ALT = &HA4
Public Const VK_BACK = &H8
Public Const VK_CANCEL = &H3
Public Const VK_CAPITAL = &H14
Public Const VK_CLEAR = &HC
Public Const VK_CONTROL = &H11
Public Const VK_CRSEL = &HF7
Public Const VK_DECIMAL = &H6E
Public Const VK_DELETE = &H2E
Public Const VK_DIVIDE = &H6F
Public Const VK_DOWN = &H28
Public Const VK_END = &H23
Public Const VK_EREOF = &HF9
Public Const VK_ESCAPE = &H1B
Public Const VK_EXECUTE = &H2B
Public Const VK_EXSEL = &HF8
Public Const VK_F1 = &H70
Public Const VK_F10 = &H79
Public Const VK_F11 = &H7A
Public Const VK_F12 = &H7B
Public Const VK_F13 = &H7C
Public Const VK_F14 = &H7D
Public Const VK_F15 = &H7E
Public Const VK_F16 = &H7F
Public Const VK_F17 = &H80
Public Const VK_F18 = &H81
Public Const VK_F19 = &H82
Public Const VK_F2 = &H71
Public Const VK_F20 = &H83
Public Const VK_F21 = &H84
Public Const VK_F22 = &H85
Public Const VK_F23 = &H86
Public Const VK_F24 = &H87
Public Const VK_F3 = &H72
Public Const VK_F4 = &H73
Public Const VK_F5 = &H74
Public Const VK_F6 = &H75
Public Const VK_F7 = &H76
Public Const VK_F8 = &H77
Public Const VK_F9 = &H78
Public Const VK_HELP = &H2F
Public Const VK_HOME = &H24
Public Const VK_INSERT = &H2D
Public Const VK_LBUTTON = &H1
Public Const VK_LCONTROL = &HA2
Public Const VK_LEFT = &H25
Public Const VK_LMENU = &HA4
Public Const VK_LSHIFT = &HA0
Public Const VK_MBUTTON = &H4
Public Const VK_MENU = &H12
Public Const VK_MULTIPLY = &H6A
Public Const VK_NEXT = &H22
Public Const VK_NONAME = &HFC
Public Const VK_NUMLOCK = &H90
Public Const VK_NUMPAD0 = &H60
Public Const VK_NUMPAD1 = &H61
Public Const VK_NUMPAD2 = &H62
Public Const VK_NUMPAD3 = &H63
Public Const VK_NUMPAD4 = &H64
Public Const VK_NUMPAD5 = &H65
Public Const VK_NUMPAD6 = &H66
Public Const VK_NUMPAD7 = &H67
Public Const VK_NUMPAD8 = &H68
Public Const VK_NUMPAD9 = &H69
Public Const VK_OEM_CLEAR = &HFE
Public Const VK_PA1 = &HFD
Public Const VK_PAUSE = &H13
Public Const VK_PLAY = &HFA
Public Const VK_PRINT = &H2A
Public Const VK_PRIOR = &H21
Public Const VK_PROCESSKEY = &HE5
Public Const VK_RBUTTON = &H2
Public Const VK_RCONTROL = &HA3
Public Const VK_RETURN = &HD
Public Const VK_RIGHT = &H27
Public Const VK_RMENU = &HA5
Public Const VK_RSHIFT = &HA1
Public Const VK_SCROLL = &H91
Public Const VK_SELECT = &H29
Public Const VK_SEPARATOR = &H6C
Public Const VK_SHIFT = &H10
Public Const VK_SNAPSHOT = &H2C
Public Const VK_SPACE = &H20
Public Const VK_SUBTRACT = &H6D
Public Const VK_TAB = &H9
Public Const VK_UP = &H26
Public Const VK_ZOOM = &HFB
Public Const VK_TILD = &HC0 '~ 문자
Public Const VK_BACKSLASH = &HDC '\ 문자

'*************스캔코드표***********************
Public Const SCANKEY_ESC = 1

Public Const SCANKEY_1 = 2             ' 1
Public Const SCANKEY_2 = 3             ' 2
Public Const SCANKEY_3 = 4             ' 3
Public Const SCANKEY_4 = 5             ' 4
Public Const SCANKEY_5 = 6             ' 5
Public Const SCANKEY_6 = 7             ' 6
Public Const SCANKEY_7 = 8             ' 7
Public Const SCANKEY_8 = 9             ' 8
Public Const SCANKEY_9 = 10            ' 9
Public Const SCANKEY_0 = 11            ' 0
Public Const SCANKEY_MINUS = 12        ' -
Public Const SCANKEY_EQUAL = 13        ' =
Public Const SCANKEY_BS = 14           ' ←

Public Const SCANKEY_TAB = 15          'TAB
Public Const SCANKEY_Q = 16            ' Q
Public Const SCANKEY_W = 17            ' W
Public Const SCANKEY_E = 18            ' E
Public Const SCANKEY_R = 19            ' R
Public Const SCANKEY_T = 20            ' T
Public Const SCANKEY_Y = 21            ' Y
Public Const SCANKEY_U = 22            ' U
Public Const SCANKEY_I = 23            ' I
Public Const SCANKEY_O = 24            ' O
Public Const SCANKEY_P = 25            ' P
Public Const SCANKEY_SQUARE_OPEN = 26  ' [
Public Const SCANKEY_SQUARE_CLOSE = 27 ' ]
Public Const SCANKEY_ENTER = 28        ' ENTER

Public Const SCANKEY_CTRL = 29         ' CTRL
Public Const SCANKEY_A = 30            ' A
Public Const SCANKEY_S = 31            ' S
Public Const SCANKEY_D = 32            ' D
Public Const SCANKEY_F = 33            ' F
Public Const SCANKEY_G = 34            ' G
Public Const SCANKEY_H = 35            ' H
Public Const SCANKEY_J = 36            ' J
Public Const SCANKEY_K = 37            ' K
Public Const SCANKEY_L = 38            ' L
Public Const SCANKEY_SEMICOLON = 39    ' ;
Public Const SCANKEY_QUOTATION = 40    ' '

Public Const SCANKEY_QUOTATION2 = 41   ' `
Public Const SCANKEY_LSHIFT = 42       ' LEFT SHIFT
Public Const SCANKEY_WON = 43          ' \

Public Const SCANKEY_Z = 44            ' Z
Public Const SCANKEY_X = 45            ' X
Public Const SCANKEY_C = 46            ' C
Public Const SCANKEY_V = 47            ' V
Public Const SCANKEY_B = 48            ' B
Public Const SCANKEY_N = 49            ' N
Public Const SCANKEY_M = 50            ' M
Public Const SCANKEY_COMMA = 51        ' ,
Public Const SCANKEY_PERIOD = 52       ' .
Public Const SCANKEY_SLASH = 53        ' /
Public Const SCANKEY_RSHIFT = 54       ' RIGHT SHIFT

Public Const SCANKEY_PRTSC = 55        ' PRINT SCREEN SYS RQ
Public Const SCANKEY_ALT = 56          ' ALT
Public Const SCANKEY_SPACE = 57        ' SPACE
Public Const SCANKEY_CAPS = 58         ' CAPS
Public Const SCANKEY_F1 = 59           ' F1
Public Const SCANKEY_F2 = 60           ' F2
Public Const SCANKEY_F3 = 61           ' F3
Public Const SCANKEY_F4 = 62           ' F4
Public Const SCANKEY_F5 = 63           ' F5
Public Const SCANKEY_F6 = 64           ' F6
Public Const SCANKEY_F7 = 65           ' F7
Public Const SCANKEY_F8 = 66           ' F8
Public Const SCANKEY_F9 = 67           ' F9
Public Const SCANKEY_F10 = 68          ' F10
Public Const SCANKEY_F11 = 87          ' F11
Public Const SCANKEY_F12 = 88          ' F12

Public Const SCANKEY_NUM = 69          ' NUM ROCK
Public Const SCANKEY_SCROLL = 70       ' SCROLL ROCK

Public Const SCANKEY_GRAY_HOME = 71    ' 키패드
Public Const SCANKEY_GRAY_UP = 72
Public Const SCANKEY_GRAY_PGUP = 73
Public Const SCANKEY_GRAY_MINUS = 74
Public Const SCANKEY_GRAY_LEFT = 75
Public Const SCANKEY_GRAY_CENTER = 76
Public Const SCANKEY_GRAY_RIGHT = 77
Public Const SCANKEY_GRAY_PLUS = 78
Public Const SCANKEY_GRAY_END = 79
Public Const SCANKEY_GRAY_DOWN = 80
Public Const SCANKEY_GRAY_PGDN = 81
Public Const SCANKEY_GRAY_INS = 82
Public Const SCANKEY_GRAY_DEL = 83

